// ============================================================================
// ui_netscan.cpp -- Content: Diagnose > Netzwerk (Tabs Netz / Funk; Body, Section in ui_diag.cpp).
//
// D3 (Netzzonen-Diagnose): Tab "Netz" = generische L3/L4-Werkzeuge fuer JEDES geroutete Netz
// (WLAN-LAN, WireGuard, IPsec-Zonenroute, ...): Host-Sweep mit Zielauswahl aus der Registry, Einzel-
// Ping, Routing-Befund (Resolve), TCP/UDP-Portscan. Kein WLAN-Wissen; Routing durch lwIP/Zonen-Runtime.
// ARP-Discovery ist eine lokale L2-Capability (Ethernet/WLAN on-link), sonst ICMP-Sweep.
// Tab "Funk" = WLAN-only (Passiv-Monitor, Kanal-Uebersicht, Tiefen-Scan) -- bei WLAN=aus ausgegraut.
// Logik: net_scan.*, Endpoints in esp32-modem-host.ino (/net-*). Konsole: 'net ...' (gleiche API).
// ============================================================================
#include "weirdos_features.h"   // WEIRDOS_FEATURE_NETSCAN
#include "web_ui.h"

#if WEIRDOS_FEATURE_NETSCAN
void renderNetScanBody(WeirdUiWriter& w, bool wifiOn, bool wifiHw) {
    w.write(
        "<div class='page-sub active' id='psub-nx-hosts'>"
        "<h2 class='section-title'>Rechner im Netz finden (Host-Sweep)</h2>"
        "<p class='cam-hint'>Sucht erreichbare Rechner in einem Netz - von der MCU aus, ueber das normale Routing "
        "(auch WireGuard- und IPsec-Netze ueber die Zonenroute). Lokale Ethernet-/WLAN-Netze: ARP-Discovery (findet "
        "auch Ping-tote Geraete); geroutete Netze: ICMP-Sweep. Maximal 512 Ziele je Sweep, groessere Netze werden "
        "abgelehnt (dann kleineres Netz eintragen).</p>"
        "<div class='cam-bar'>"
        "<select id='ns-target' class='cam-select cfg-select' style='max-width:340px'><option value=''>Ziele werden geladen ...</option></select>"
        "<input id='ns-cidr' type='text' autocomplete='off' placeholder='oder Netz a.b.c.d/n' style='max-width:170px'>"
        "<select id='ns-mode' class='cam-select cfg-select' style='max-width:120px'>"
        "<option value='auto'>automatisch</option><option value='arp'>ARP (L2)</option><option value='icmp'>ICMP (L3)</option></select>"
        "<button id='ns-scan' class='cam-button' type='button'>Sweep starten</button>"
        "<span id='ns-state' class='scan-status'></span>"
        "</div>"
        "<div id='ns-hosts' class='info'></div>"

        "<h2 class='section-title'>Einzelnen Rechner anpingen / Routing-Befund</h2>"
        "<p class='cam-hint'>Ping geht vom P4 aus durch lwIP. &quot;Weg&quot; zeigt den lokalen Routing-Befund fuer die IP "
        "(Ausgangsinterface, Anbindung, Zonenroute, TSr-Deckung). Verkehr vom P4 selbst durchlaeuft KEINE Zonen-Policy; "
        "mit &quot;von&quot; wird zusaetzlich die Forward-Policy dieser Quelle (ROUTE/NAT/SNAT) gezeigt.</p>"
        "<div class='cam-bar'>"
        "<input id='ns-ip' type='text' autocomplete='off' placeholder='192.168.110.209' style='max-width:170px'>"
        "<button id='ns-ping' class='cam-button' type='button'>Ping</button>"
        "<select id='ns-from' class='cam-select cfg-select' style='max-width:200px'><option value=''>von: (nur lokal)</option></select>"
        "<button id='ns-resolve' class='cam-button' type='button'>Weg</button>"
        "<span id='ns-ping-res' class='scan-status'></span>"
        "</div>"
        "<div id='ns-resolve-out' class='info'></div>"

        "<h2 class='section-title'>Port-Scan (TCP/UDP)</h2>"
        "<p class='cam-hint'>Findet offene Ports - auch auf Rechnern, die kein Ping beantworten, in jedem gerouteten Netz. "
        "&quot;Haeufige Ports&quot; scannt eine Auswahl; fuer einen Bereich von/bis eintragen (max. 4096 TCP / 512 UDP je Lauf; groessere Bereiche werden abgelehnt, nicht gekappt -- in Bloecken scannen).</p>"
        "<div class='cam-bar'>"
        "<input id='ps-ip' type='text' autocomplete='off' placeholder='192.168.110.209' style='max-width:150px'>"
        "<select id='ps-proto' class='cam-select cfg-select' style='max-width:90px'>"
        "<option value='tcp'>TCP</option><option value='udp'>UDP</option></select>"
        "<button id='ps-common' class='cam-button' type='button'>Haeufige Ports</button>"
        "<input id='ps-from' type='number' min='1' max='65535' placeholder='von' style='max-width:80px'>"
        "<input id='ps-to' type='number' min='1' max='65535' placeholder='bis' style='max-width:80px'>"
        "<button id='ps-range' class='cam-button' type='button'>Bereich</button>"
        "</div>"
        "<span id='ps-state' class='scan-status'></span>"
        "<div id='ps-open' class='info'></div>"
        "</div>"   // /psub-nx-hosts

        "<div class='page-sub' id='psub-nx-funk'>");
    if (!wifiOn) {
        w.write(
            "<div style='border-left:4px solid #e0a800;background:#fff8e6;padding:10px 12px;"
            "border-radius:6px;margin:8px 0'><p><strong>WLAN-Stack ist aus</strong> -- ");
        w.write(wifiHw
            ? "unter LAN &gt; WLAN auf &quot;Aus&quot; gestellt. Die Funk-Werkzeuge (Passiv-Monitor, Kanal-Scans) "
              "setzen einen laufenden WLAN-Stack voraus; dort auf &quot;Automatisch&quot; oder &quot;Immer an&quot; "
              "stellen und neu starten. Die Werkzeuge im Tab &quot;Netz&quot; funktionieren unabhaengig davon."
            : "WLAN ist nicht im Build (Baustein WIFI): entweder hat dieser Chip keinen WLAN-Funk (ESP32-P4: nur ueber "
              "ESP-Hosted + Companion-C6, nicht bestueckt) oder der Baustein wurde beim Bauen abgewaehlt. "
              "Die Funk-Werkzeuge (Passiv-Monitor, Kanal-Scans) sind deshalb nicht nutzbar; die Werkzeuge im Tab "
              "&quot;Netz&quot; funktionieren unabhaengig davon.");
        w.write("</p></div><div class='fields-inactive'>");
    }
    w.write(
        "<h2 class='section-title'>Passiv-Monitor (WLAN mithoeren)</h2>"
        "<p class='cam-hint'>Hoert das WLAN passiv mit und listet <b>sendende</b> Geraete (MAC + Signal) - "
        "findet auch Rechner, die auf Ping/TCP/ARP schweigen. WPA2: nur MAC/Signal sichtbar, keine IPs "
        "(Payload verschluesselt); bekannte MACs werden mit dem letzten ARP-Sweep zu IPs aufgeloest. Waehrend des "
        "Mithoerens kann die WLAN-Verbindung kurz zaeh werden.</p>"
        "<div class='cam-bar'>"
        "<button id='sn-start' class='cam-button' type='button'>Mithoeren (8s)</button>"
        "<span id='sn-state' class='scan-status'></span>"
        "</div>"
        "<div id='sn-list' class='info'></div>"

        "<h2 class='section-title'>Kanal-Uebersicht (WLAN optimieren)</h2>"
        "<p class='cam-hint'>Scannt alle Frequenzen: Zahl der Funknetze (APs) je Kanal + staerkstes Signal "
        "+ ueberlappungsgewichtete Stoerlast. Empfiehlt den freiesten Kanal (1/6/11). Der eigene WLAN-Empfang "
        "setzt waehrend des Scans (~3s) kurz aus.</p>"
        "<div class='cam-bar'>"
        "<button id='ch-start' class='cam-button' type='button'>Kanal-Scan</button>"
        "<span id='ch-state' class='scan-status'></span>"
        "</div>"
        "<div id='ch-graph' style='margin:8px 0'></div>"
        "<div id='ch-list' class='info'></div>"

        "<h2 class='section-title'>Tiefen-Scan (Geraete je Kanal)</h2>"
        "<p class='cam-hint'>Springt aktiv ueber alle Kanaele und zaehlt <b>sendende Geraete + Traffic</b> je "
        "Kanal - die tatsaechliche Auslastung, nicht nur APs. <b>Achtung:</b> das eigene WLAN ist dabei ~17s "
        "getrennt, die Ergebnisse erscheinen danach. (Wer ueber Mobilfunk/DynDNS zugreift, merkt nichts.)</p>"
        "<div class='cam-bar'>"
        "<button id='dc-start' class='cam-button' type='button'>Tiefen-Scan (WLAN ~17s weg)</button>"
        "<span id='dc-state' class='scan-status'></span>"
        "</div>"
        "<div id='dc-list' class='info'></div>");
    if (!wifiOn) w.write("</div>");
    w.write(
        "<script>(function(){"
        "var poll=null;"
        "function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;');}"
        // --- Ziele aus der Registry (Attachments + routingfaehige Prefixe) ---
        "function loadTargets(){fetch('/net-scan-targets.json?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(list){"
          "var s=document.getElementById('ns-target');if(!s)return;var x='';"
          "if(!list||!list.length)x='<option value=\"\">keine aktiven Netze in der Registry</option>';"
          "for(var i=0;i<list.length;i++){var t=list[i];x+='<option value=\"'+esc(t.target)+'\"'+(t.tooBig?' disabled':'')+'>'+esc(t.attachment)+' - '+esc(t.net)+'/'+t.prefix+' ('+(t.l2?'ARP/L2':'ICMP/L3')+', '+t.hosts+' Hosts'+(t.tooBig?', zu gross':'')+')</option>';}"
          "s.innerHTML=x;"
          "var f=document.getElementById('ns-from');if(f){var y='<option value=\"\">von: (nur lokal)</option>';var seen={};"
            "for(var i=0;i<list.length;i++){var a=list[i].attachment;if(seen[a])continue;seen[a]=1;y+='<option value=\"'+esc(a)+'\">von: '+esc(a)+'</option>';}f.innerHTML=y;}"
        "}).catch(function(){});}"
        "loadTargets();"
        // --- Sweep ---
        "function render(d){"
          "var st=document.getElementById('ns-state');"
          "if(st)st.textContent=d.error?('Fehler: '+d.error):(d.running?('scanne '+d.scanned+'/'+d.total+' ('+(d.target||'')+', '+(d.mode||'')+' ueber '+(d.egress||'?')+') ...')"
            ":('fertig - '+((d.hosts&&d.hosts.length)||0)+' Geraete in '+(d.target||'')+' ('+(d.mode||'')+' ueber '+(d.egress||'?')+')'));"
          "var h=document.getElementById('ns-hosts');if(!h)return;var x='';"
          "if(d.hosts&&d.hosts.length){for(var i=0;i<d.hosts.length;i++){var c=d.hosts[i];"
            "x+='<div><span>'+esc(c.ip)+(c.mac?(' <small>'+esc(c.mac)+(c.vendor?(' ['+esc(c.vendor)+']'):'')+'</small>'):'')+'</span><span>'"
              "+(c.ms>=0?(c.ms+' ms'):'kein Ping')+' '"
              "+'<button class=\"cam-button ns-p\" type=\"button\" data-ip=\"'+esc(c.ip)+'\">Ping</button></span></div>';}}"
          "else if(!d.running&&!d.error){x='<div><span>Keine Geraete gefunden</span><span></span></div>';}"
          "h.innerHTML=x;"
        "}"
        "function tick(){fetch('/net-scan.json?t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){render(d);"
          "if(!d.running&&poll){clearInterval(poll);poll=null;}}).catch(function(){});}"
        "var b=document.getElementById('ns-scan');"
        "if(b)b.addEventListener('click',function(){var c=(document.getElementById('ns-cidr')||{}).value||'';var t=c.trim()||((document.getElementById('ns-target')||{}).value||'');"
          "var m=(document.getElementById('ns-mode')||{}).value||'auto';"
          "fetch('/net-scan-start',{method:'POST',cache:'no-store',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'target='+encodeURIComponent(t)+'&mode='+encodeURIComponent(m)})"
          ".then(function(r){return r.json();}).then(function(d){var st=document.getElementById('ns-state');if(!d.ok){if(st)st.textContent='Fehler: '+d.msg;return;}"
          "if(poll)clearInterval(poll);poll=setInterval(tick,1200);tick();}).catch(function(){});});"
        // --- Ping + Resolve ---
        "function pingIp(ip,el,shrt){if(!ip)return;if(el)el.textContent=shrt?'...':'pinge '+ip+' ...';"
          "fetch('/net-ping?ip='+encodeURIComponent(ip)+'&t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){"
          "if(el)el.textContent=shrt?(d.up?(d.ms+' ms'):'weg'):(d.up?(ip+' antwortet ('+d.ms+' ms)'):(ip+' antwortet NICHT'));})"
          ".catch(function(){if(el)el.textContent='Fehler';});}"
        "var pb=document.getElementById('ns-ping');"
        "if(pb)pb.addEventListener('click',function(){var i=document.getElementById('ns-ip');"
          "pingIp(i?i.value:'',document.getElementById('ns-ping-res'),false);});"
        "function row(k,v){return '<div><span>'+esc(k)+'</span><span>'+esc(v)+'</span></div>';}"
        "var rb=document.getElementById('ns-resolve');"
        "if(rb)rb.addEventListener('click',function(){var ip=((document.getElementById('ns-ip')||{}).value||'').trim();var from=(document.getElementById('ns-from')||{}).value||'';var o=document.getElementById('ns-resolve-out');if(!ip||!o)return;"
          "fetch('/net-resolve?ip='+encodeURIComponent(ip)+'&from='+encodeURIComponent(from)+'&t='+Date.now(),{cache:'no-store'}).then(function(r){return r.json();}).then(function(d){"
          "if(!d.ok){o.innerHTML=row('Fehler',d.msg);return;}var l=d.local||{};var x='';"
          "x+=row('Lokaler Weg (vom P4)', (l.egress||'-')+' = '+(l.iface||'?')+(l.attachment?(' / '+l.attachment):'')+(l.egressIp?(' ('+l.egressIp+')'):''));"
          "x+=row('Routenart', l.routeKind==='zone'?('Zonenroute '+l.zoneRoute):l.routeKind==='zone-block'?('Zonenroute '+l.zoneRoute+' = BLOCK (fail-closed)'):l.routeKind==='default'?'Standardroute (Uplink) - NICHT ueber ein Zonen-/VPN-Netz':l.routeKind==='onlink'?'on-link / Interface-Netz':'kein Ausgang');"
          "if(l.covered)x+=row('Gedeckt durch', l.covered+' ('+(l.coveredSource||'')+')');"
          "if(typeof l.tsrCovered!=='undefined')x+=row('IPsec TSr-Deckung', l.tsrCovered?'ja':'NEIN - Gateway wird das Paket verwerfen');"
          "x+=row('Hinweis', l.note||'');"
          "if(d.from){var f=d.from,p=f.policy||{};x+=row('Forward-Policy '+f.attachment+' -> '+(f.dst||'?'), (p.installed?('installiert: '+p.mode):('nicht installiert: '+p.mode))+(p.natSource?(' SNAT '+p.natSource):'')+' - '+(p.reason||''));"
            "if(f.preview&&f.preview.pair)x+=row('Planner-Vorschau (technisch)', f.preview.pair.mode+' - '+(f.preview.pair.reason||''));}"
          "o.innerHTML=x;}).catch(function(){o.innerHTML=row('Fehler','keine Antwort');});});"
        "var hs=document.getElementById('ns-hosts');"
        "if(hs)hs.addEventListener('click',function(e){var t=e.target;"
          "if(t&&t.classList&&t.classList.contains('ns-p')){var ip=t.getAttribute('data-ip');"
            "var pi=document.getElementById('ps-ip');if(pi)pi.value=ip;var ni=document.getElementById('ns-ip');if(ni)ni.value=ip;"
            "pingIp(ip,t,true);}});"
        // --- Port-Scan ---
        "var pp=null;"
        "function psRender(d){var st=document.getElementById('ps-state');var rg=d.common?'Haeufige Ports':('Bereich '+d.from+'-'+d.to);"
          "if(st)st.textContent=(d.ip?(d.ip+' ('+(d.proto||'tcp').toUpperCase()+', '+rg+'): '):'')+(d.running?('scanne '+d.scanned+'/'+d.total+' ...')"
            ":('fertig - '+((d.open&&d.open.length)||0)+' offen von '+d.total+' gescannt'));"
          "var o=document.getElementById('ps-open');if(!o)return;var x='';"
          "if(d.open&&d.open.length){for(var i=0;i<d.open.length;i++){var p=d.open[i];"
            "x+='<div><span>'+(d.proto||'tcp').toUpperCase()+' '+p.port+(p.svc?(' ('+p.svc+')'):'')+'</span><span>'+(p.state||'offen')+'</span></div>';}}"
          "else if(!d.running){x='<div><span>Keine offenen Ports gefunden</span><span></span></div>';}o.innerHTML=x;}"
        "function psTick(){fetch('/net-portscan.json?t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){psRender(d);"
          "if(!d.running&&pp){clearInterval(pp);pp=null;}}).catch(function(){});}"
        "function psStart(body){fetch('/net-portscan-start',{method:'POST',cache:'no-store',"
          "headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body})"
          ".then(function(r){return r.json();}).then(function(d){var st=document.getElementById('ps-state');"
          "if(!d.ok){if(st)st.textContent='Abgelehnt: '+d.msg;return;}"   // zu grosser Bereich: Grund zeigen, nichts gekappt
          "if(pp)clearInterval(pp);pp=setInterval(psTick,1000);psTick();}).catch(function(){});}"
        "function psIp(){var e=document.getElementById('ps-ip');return e?e.value.trim():'';}"
        "function psProto(){var e=document.getElementById('ps-proto');return '&proto='+((e&&e.value)||'tcp');}"
        "var pc=document.getElementById('ps-common');"
        "if(pc)pc.addEventListener('click',function(){var ip=psIp();if(ip)psStart('ip='+encodeURIComponent(ip)+psProto());});"
        "var pr=document.getElementById('ps-range');"
        "if(pr)pr.addEventListener('click',function(){var ip=psIp();"
          "var f=(document.getElementById('ps-from')||{}).value,t=(document.getElementById('ps-to')||{}).value;"
          "if(ip&&f&&t)psStart('ip='+encodeURIComponent(ip)+'&from='+encodeURIComponent(f)+'&to='+encodeURIComponent(t)+psProto());});"
        // --- Passiv-Monitor ---
        "var sp=null;"
        "function snRender(d){var st=document.getElementById('sn-state');"
          "if(st)st.textContent=d.running?('mithoeren... '+d.left+'s'):('fertig - '+((d.devices&&d.devices.length)||0)+' Geraete gehoert');"
          "var l=document.getElementById('sn-list');if(!l)return;var x='';"
          "if(d.devices&&d.devices.length){d.devices.sort(function(a,b){return b.rssi-a.rssi;});"
            "for(var i=0;i<d.devices.length;i++){var g=d.devices[i];"
            "x+='<div><span>'+esc(g.mac)+(g.vendor?(' ['+esc(g.vendor)+']'):'')+(g.ip?(' <small>'+esc(g.ip)+'</small>'):'')+'</span><span>'"
              "+g.rssi+' dBm, '+g.count+' Pkt ('+g.type+')</span></div>';}}"
          "else if(!d.running){x='<div><span>Keine Geraete gehoert</span><span></span></div>';}l.innerHTML=x;}"
        "function snTick(){fetch('/net-sniff.json?t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){snRender(d);"
          "if(!d.running&&sp){clearInterval(sp);sp=null;}}).catch(function(){});}"
        "var sb=document.getElementById('sn-start');"
        "if(sb)sb.addEventListener('click',function(){fetch('/net-sniff-start?secs=8',{method:'POST',cache:'no-store'})"
          ".then(function(){if(sp)clearInterval(sp);sp=setInterval(snTick,1200);snTick();});});"
        // --- Kanal-Uebersicht ---
        "var cp=null;"
        "var CCOL=['#2f6fd0','#2e9e5b','#d9822b','#c0392b','#8e44ad','#16a085','#e67e22','#2c3e50','#d81b60','#00838f'];"
        "function chGraph(aps){var W=520,H=150,pl=10,pr=10,pt=10,pb=18;var cw=(W-pl-pr)/12;var base=H-pb;"
          "function xc(c){return pl+(c-1)*cw;}function yr(r){var s=Math.max(-100,Math.min(-30,r));return pt+(-30-s)/70*(H-pt-pb);}"
          "var s='<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 '+W+' '+H+'\" width=\"100%\" style=\"max-width:520px;background:#fff;border:1px solid #d7dbe0;border-radius:6px\">';"
          "for(var c=1;c<=13;c++){var x=xc(c);s+='<line x1=\"'+x+'\" y1=\"'+pt+'\" x2=\"'+x+'\" y2=\"'+base+'\" stroke=\"#eef1f4\"/>';"
            "s+='<text x=\"'+x+'\" y=\"'+(H-5)+'\" font-size=\"8\" text-anchor=\"middle\" fill=\"#999\">'+c+'</text>';}"
          "for(var i=0;i<aps.length;i++){var a=aps[i];if(a.ch<1||a.ch>13)continue;var col=CCOL[i%CCOL.length];"
            "var x=xc(a.ch),yp=yr(a.rssi),xl=x-2*cw,xr=x+2*cw,yq=2*yp-base;"
            "s+='<path d=\"M '+xl.toFixed(1)+' '+base+' Q '+x.toFixed(1)+' '+yq.toFixed(1)+' '+xr.toFixed(1)+' '+base+'\" fill=\"'+col+'22\" stroke=\"'+col+'\" stroke-width=\"1.3\"/>';"
            "s+='<text x=\"'+x.toFixed(1)+'\" y=\"'+(yp-3).toFixed(1)+'\" font-size=\"8\" text-anchor=\"middle\" fill=\"'+col+'\">'+esc((a.ssid||'?').substring(0,12))+'</text>';}"
          "return s+'</svg>';}"
        "function chRender(d){var st=document.getElementById('ch-state');"
          "if(st)st.textContent=d.running?'scanne Kanaele...':('Empfehlung: Kanal '+d.recommend);"
          "var gr=document.getElementById('ch-graph');if(gr&&d.aps)gr.innerHTML=chGraph(d.aps);"
          "var l=document.getElementById('ch-list');if(!l||!d.channels)return;var mx=1;"
          "for(var i=0;i<d.channels.length;i++)if(d.channels[i].score>mx)mx=d.channels[i].score;"
          "var x='';for(var i=0;i<d.channels.length;i++){var c=d.channels[i];var w=Math.round(c.score*110/mx);"
            "var rec=(c.ch==d.recommend);"
            "x+='<div><span>Kanal '+c.ch+(rec?' &#9733;':'')+'</span><span>'+c.aps+' APs'+(c.aps>0?(', '+c.rssi+' dBm'):'')"
              "+' <span style=\"display:inline-block;height:8px;width:'+w+'px;background:'+(rec?'#2e9e5b':'#2f6fd0')+';border-radius:4px;vertical-align:middle\"></span></span></div>';}"
          "l.innerHTML=x;}"
        "function chTick(){fetch('/net-chscan.json?t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){chRender(d);"
          "if(!d.running&&cp){clearInterval(cp);cp=null;}}).catch(function(){});}"
        "var cbtn=document.getElementById('ch-start');"
        "if(cbtn)cbtn.addEventListener('click',function(){var st=document.getElementById('ch-state');"
          "if(st)st.textContent='scanne Kanaele (WLAN kurz weg)...';"
          "fetch('/net-chscan-start',{method:'POST',cache:'no-store'}).then(function(){"
          "if(cp)clearInterval(cp);cp=setInterval(chTick,1500);setTimeout(chTick,3800);}).catch(function(){});});"
        // --- Tiefen-Scan (Channel-Hopping) ---
        "var dp=null;"
        "function dcRender(d){var st=document.getElementById('dc-state');"
          "if(st)st.textContent=d.running?('scanne Kanal '+d.cur+'/13 ...'):'fertig';"
          "var l=document.getElementById('dc-list');if(!l||!d.channels)return;var mx=1;"
          "for(var i=0;i<d.channels.length;i++)if(d.channels[i].pkts>mx)mx=d.channels[i].pkts;"
          "var x='';for(var i=0;i<d.channels.length;i++){var c=d.channels[i];var w=Math.round(c.pkts*110/mx);"
            "x+='<div><span>Kanal '+c.ch+'</span><span>'+c.devices+' Geraete, '+c.pkts+' Pkt '"
              "+'<span style=\"display:inline-block;height:8px;width:'+w+'px;background:#8e44ad;border-radius:4px;vertical-align:middle\"></span></span></div>';}"
          "l.innerHTML=x;}"
        "function dcTick(){fetch('/net-deepch.json?t='+Date.now(),{cache:'no-store'})"
          ".then(function(r){return r.json();}).then(function(d){dcRender(d);"
          "if(!d.running&&dp){clearInterval(dp);dp=null;}}).catch(function(){});}"
        "var db=document.getElementById('dc-start');"
        "if(db)db.addEventListener('click',function(){var st=document.getElementById('dc-state');"
          "if(st)st.textContent='WLAN wird getrennt, ~20s warten...';"
          "fetch('/net-deepch-start',{method:'POST',cache:'no-store'}).then(function(){"
          "if(dp)clearInterval(dp);dp=setInterval(dcTick,2000);}).catch(function(){if(dp)clearInterval(dp);dp=setInterval(dcTick,2000);});});"
        "})();</script>"
        "</div>"   // /psub-nx-funk
    );
}
#else
// Netzwerk-Diagnose nicht im Build (WEIRDOS_FEATURE_NETSCAN=0). Beide Unterseiten (Netz / Funk) bleiben
// sichtbar und nennen den Grund -- Menuepunkt nicht verstecken (Konsistenz mit Netzzonen/Bluetooth).
// Bewusst OHNE Bedien-IDs und OHNE Poll-Script: die /net-*-Routen sind in diesem Build nicht
// registriert (Routen in der .ino ebenfalls unter WEIRDOS_FEATURE_NETSCAN).
void renderNetScanBody(WeirdUiWriter& w, bool wifiOn, bool wifiHw) {
    (void)wifiOn; (void)wifiHw;
    w.write(
        "<div class='page-sub active' id='psub-nx-hosts'>"
        "<h2 class='section-title'>Netzwerk-Diagnose</h2>"
        "<div style='border-left:4px solid #e0a800;background:#fff8e6;padding:10px 12px;"
        "border-radius:6px;margin:8px 0'><p><strong>Die Netzwerk-Diagnose ist in diesem Build nicht enthalten "
        "(WEIRDOS_FEATURE_NETSCAN=0).</strong> Der Baustein NETSCAN (Host-Sweep, Ping, Routing-Befund, "
        "TCP/UDP-Portscan, Passiv-Monitor und Kanalscan) wurde beim Bauen abgewaehlt.</p></div>"
        "<div class='fields-inactive'><p class='cam-hint'>Mit dem Baustein NETSCAN bietet diese Seite: Rechner im "
        "Netz finden (ARP/ICMP, auch durch WireGuard- und IPsec-Netze), Einzel-Ping mit Routing-Befund, "
        "TCP/UDP-Portscan sowie die WLAN-Funkwerkzeuge. Dieselben Werkzeuge sind dann auf der Konsole als "
        "<code>net ...</code> verfuegbar.</p></div>"
        "</div>"
        "<div class='page-sub' id='psub-nx-funk'>"
        "<h2 class='section-title'>Funk (WLAN)</h2>"
        "<p class='cam-hint'>Passiv-Monitor, Kanal-Uebersicht und Tiefen-Scan gehoeren zum Baustein NETSCAN und "
        "sind in diesem Build nicht enthalten.</p>"
        "</div>"
    );
}
#endif // WEIRDOS_FEATURE_NETSCAN
